export const CategoryList = [
  {type: 'Income', category: 'Salary', icon: ''},
  {type: 'Income', category: 'Investment', icon: ''},
  {type: 'Income', category: 'Interest', icon: ''},
  {type: 'Income', category: 'Gift', icon: ''},
  {type: 'Income', category: 'Prize', icon: ''},
  {type: 'Income', category: 'Other', icon: ''},
  {type: 'Expense', category: 'Utilities', icon: ''},
  {type: 'Expense', category: 'Bill', icon: ''},
  {type: 'Expense', category: 'Housing', icon: ''},
  {type: 'Expense', category: 'Internet', icon: ''},
  {type: 'Expense', category: 'Phone', icon: ''},
  {type: 'Expense', category: 'Rent', icon: ''},
  {type: 'Expense', category: 'Tax', icon: ''},
  {type: 'Expense', category: 'Education', icon: ''},
  {type: 'Expense', category: 'Business', icon: ''},
  {type: 'Expense', category: 'Vehicle', icon: ''},
  {type: 'Expense', category: 'Shopping', icon: ''},
  {type: 'Expense', category: 'Supplies', icon: ''},
  {type: 'Expense', category: 'Other', icon: ''},
  {type: 'Transfer', category: 'Transfer', icon: ''},
] as const;
